/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package se.vgregion.delegation.ws;

import java.util.logging.Logger;

import javax.jws.WebService;

import se.riv.authorization.delegation.savedelegations.v1.rivtabp21.SaveDelegationsResponderInterface;
import se.riv.authorization.delegation.savedelegationsresponder.v1.SaveDelegationsResponseType;

/**
 * This class was generated by Apache CXF 2.2.2 Wed Apr 18 14:42:43 CEST 2012 Generated source version: 2.2.2
 * 
 */

@WebService(serviceName = "SaveDelegationsResponderService", endpointInterface = "se.riv.authorization.delegation.savedelegations.v1.rivtabp21.SaveDelegationsResponderInterface", portName = "SaveDelegationsResponderPort", targetNamespace = "urn:riv:authorization:delegation:SaveDelegations:1:rivtabp21", wsdlLocation = "file:/Clients/vgr/scr/delegation/generated-scripts/jaxws/../../schemas/interactions/SaveDelegationsInteraction/SaveDelegationsInteraction_1.0_RIVTABP21.wsdl")
public class SaveDelegationsResponderInterfaceImpl implements SaveDelegationsResponderInterface {

    private static final Logger LOG = Logger.getLogger(SaveDelegationsResponderInterfaceImpl.class.getName());

    public SaveDelegationsResponderInterfaceImpl() {

        super();
        System.out.println("hej");

    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * se.riv.authorization.delegation.savedelegations.v1.rivtabp21.SaveDelegationsResponderInterface#saveDelegations
     * (java.lang.String logicalAddress
     * ,)se.riv.authorization.delegation.savedelegationsresponder.v1.SaveDelegationsType parameters )*
     */
    @Override
    public se.riv.authorization.delegation.savedelegationsresponder.v1.SaveDelegationsResponseType saveDelegations(
            java.lang.String logicalAddress,
            se.riv.authorization.delegation.savedelegationsresponder.v1.SaveDelegationsType parameters) {
        LOG.info("Executing operation saveDelegations");
        System.out.println(logicalAddress);
        System.out.println("DelegatedBy: " + parameters.getDelegatedBy());
        try {
            se.riv.authorization.delegation.savedelegationsresponder.v1.SaveDelegationsResponseType _return =
                    new SaveDelegationsResponseType();
            System.out.println("set comment apa");
            _return.setComment("apa");
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
